import type { Metadata } from "next";
import { Session } from "./Session";
import "./globals.css";

export const metadata: Metadata = {
  title: "ATC Monitoring System",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Session>{children}</Session>
      </body>
    </html>
  );
}
