-- Data-only migration: seed REGULAR_WORKER employees on first deploy.
-- Generated 2026-05-15T07:42:04.662Z from the local development DB.
-- Count: 23
--
-- INSERT IGNORE: skips on PK collision so this migration is no-op on a
-- target DB that already has these UUIDs. If production already holds
-- different rows for the same people (different UUIDs), this will
-- create duplicates — clean those up beforehand or delete this migration.

INSERT IGNORE INTO `employees` (`employee_id`, `first_name`, `middle_name`, `last_name`, `position`, `employee_type`, `status`, `contact_number`, `remarks`, `branch_id`, `birthday`, `date_hired`, `address`, `tin`, `sss_number`, `philhealth_number`, `pagibig_number`, `emergency_contact_name`, `emergency_contact_number`, `salary_type`, `worker_type`, `declaration_status`, `default_daily_rate`, `default_monthly_salary`, `default_auction_rate`, `default_container_rate`, `default_ot_hour_rate`, `default_ot_minute_rate`)
VALUES ('998d35a4-8dd4-4710-af1f-276e467c6646', 'SONIA', '', 'AGAPAY', '', 'REGULAR', 'ACTIVE', '', '', 'bd163cce-98e5-4513-b69e-875bd89c5f5c', NULL, NULL, '', '', '', '', '', '', '', 'FIXED_MONTHLY', 'REGULAR_WORKER', 'DECLARED', 0, 15000, NULL, NULL, NULL, NULL);

INSERT IGNORE INTO `employees` (`employee_id`, `first_name`, `middle_name`, `last_name`, `position`, `employee_type`, `status`, `contact_number`, `remarks`, `branch_id`, `birthday`, `date_hired`, `address`, `tin`, `sss_number`, `philhealth_number`, `pagibig_number`, `emergency_contact_name`, `emergency_contact_number`, `salary_type`, `worker_type`, `declaration_status`, `default_daily_rate`, `default_monthly_salary`, `default_auction_rate`, `default_container_rate`, `default_ot_hour_rate`, `default_ot_minute_rate`)
VALUES ('1b32d9e3-cc0a-4337-ac9a-877c624a987b', 'SHIENNA', NULL, 'CABRERA', NULL, 'REGULAR', 'ACTIVE', NULL, NULL, 'bd163cce-98e5-4513-b69e-875bd89c5f5c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FIXED_MONTHLY', 'REGULAR_WORKER', 'NON_DECLARED', NULL, 6600, 700, NULL, 93.75, 1.56);

INSERT IGNORE INTO `employees` (`employee_id`, `first_name`, `middle_name`, `last_name`, `position`, `employee_type`, `status`, `contact_number`, `remarks`, `branch_id`, `birthday`, `date_hired`, `address`, `tin`, `sss_number`, `philhealth_number`, `pagibig_number`, `emergency_contact_name`, `emergency_contact_number`, `salary_type`, `worker_type`, `declaration_status`, `default_daily_rate`, `default_monthly_salary`, `default_auction_rate`, `default_container_rate`, `default_ot_hour_rate`, `default_ot_minute_rate`)
VALUES ('8868e547-1a21-456b-9f1b-3429040558a4', 'JUDY LAINE', NULL, 'CARENCIA', NULL, 'REGULAR', 'ACTIVE', NULL, NULL, 'bd163cce-98e5-4513-b69e-875bd89c5f5c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FIXED_MONTHLY', 'REGULAR_WORKER', 'DECLARED', NULL, 9750, NULL, NULL, NULL, NULL);

INSERT IGNORE INTO `employees` (`employee_id`, `first_name`, `middle_name`, `last_name`, `position`, `employee_type`, `status`, `contact_number`, `remarks`, `branch_id`, `birthday`, `date_hired`, `address`, `tin`, `sss_number`, `philhealth_number`, `pagibig_number`, `emergency_contact_name`, `emergency_contact_number`, `salary_type`, `worker_type`, `declaration_status`, `default_daily_rate`, `default_monthly_salary`, `default_auction_rate`, `default_container_rate`, `default_ot_hour_rate`, `default_ot_minute_rate`)
VALUES ('7bc0ea22-e8c2-4d58-9999-0528b4c1ee38', 'CHELSIE', NULL, 'CLEMENTE', NULL, 'REGULAR', 'ACTIVE', NULL, NULL, 'bd163cce-98e5-4513-b69e-875bd89c5f5c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FIXED_MONTHLY', 'REGULAR_WORKER', 'NON_DECLARED', NULL, 6300, 700, NULL, 93.75, 1.56);

INSERT IGNORE INTO `employees` (`employee_id`, `first_name`, `middle_name`, `last_name`, `position`, `employee_type`, `status`, `contact_number`, `remarks`, `branch_id`, `birthday`, `date_hired`, `address`, `tin`, `sss_number`, `philhealth_number`, `pagibig_number`, `emergency_contact_name`, `emergency_contact_number`, `salary_type`, `worker_type`, `declaration_status`, `default_daily_rate`, `default_monthly_salary`, `default_auction_rate`, `default_container_rate`, `default_ot_hour_rate`, `default_ot_minute_rate`)
VALUES ('2b1831c9-5602-41f7-a5a0-81b23c150521', 'KRIS', '', 'COS', '', 'REGULAR', 'ACTIVE', '', '', 'bd163cce-98e5-4513-b69e-875bd89c5f5c', NULL, NULL, '', '', '', '', '', '', '', 'FIXED_MONTHLY', 'REGULAR_WORKER', 'NON_DECLARED', 0, 13000, NULL, NULL, NULL, NULL);

INSERT IGNORE INTO `employees` (`employee_id`, `first_name`, `middle_name`, `last_name`, `position`, `employee_type`, `status`, `contact_number`, `remarks`, `branch_id`, `birthday`, `date_hired`, `address`, `tin`, `sss_number`, `philhealth_number`, `pagibig_number`, `emergency_contact_name`, `emergency_contact_number`, `salary_type`, `worker_type`, `declaration_status`, `default_daily_rate`, `default_monthly_salary`, `default_auction_rate`, `default_container_rate`, `default_ot_hour_rate`, `default_ot_minute_rate`)
VALUES ('620e7219-8012-4023-bf4f-24ac376b661e', 'RAYMOND', NULL, 'DE LAPAZ', NULL, 'REGULAR', 'ACTIVE', NULL, NULL, 'bd163cce-98e5-4513-b69e-875bd89c5f5c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FIXED_MONTHLY', 'REGULAR_WORKER', 'DECLARED', NULL, 7200, NULL, NULL, 93.75, 1.56);

INSERT IGNORE INTO `employees` (`employee_id`, `first_name`, `middle_name`, `last_name`, `position`, `employee_type`, `status`, `contact_number`, `remarks`, `branch_id`, `birthday`, `date_hired`, `address`, `tin`, `sss_number`, `philhealth_number`, `pagibig_number`, `emergency_contact_name`, `emergency_contact_number`, `salary_type`, `worker_type`, `declaration_status`, `default_daily_rate`, `default_monthly_salary`, `default_auction_rate`, `default_container_rate`, `default_ot_hour_rate`, `default_ot_minute_rate`)
VALUES ('4d630093-bb86-470e-ad85-244670575d8f', 'MARILYN', NULL, 'DE MESA', NULL, 'REGULAR', 'ACTIVE', NULL, NULL, 'bd163cce-98e5-4513-b69e-875bd89c5f5c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FIXED_MONTHLY', 'REGULAR_WORKER', 'NON_DECLARED', NULL, 6600, 700, NULL, 93.75, 1.56);

INSERT IGNORE INTO `employees` (`employee_id`, `first_name`, `middle_name`, `last_name`, `position`, `employee_type`, `status`, `contact_number`, `remarks`, `branch_id`, `birthday`, `date_hired`, `address`, `tin`, `sss_number`, `philhealth_number`, `pagibig_number`, `emergency_contact_name`, `emergency_contact_number`, `salary_type`, `worker_type`, `declaration_status`, `default_daily_rate`, `default_monthly_salary`, `default_auction_rate`, `default_container_rate`, `default_ot_hour_rate`, `default_ot_minute_rate`)
VALUES ('f7b56eb6-d930-43a2-b162-b2b5ada61652', 'JACKIE', NULL, 'DE OCAMPO', NULL, 'REGULAR', 'ACTIVE', NULL, NULL, 'bd163cce-98e5-4513-b69e-875bd89c5f5c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FIXED_MONTHLY', 'REGULAR_WORKER', 'NON_DECLARED', NULL, 14238, NULL, NULL, NULL, NULL);

INSERT IGNORE INTO `employees` (`employee_id`, `first_name`, `middle_name`, `last_name`, `position`, `employee_type`, `status`, `contact_number`, `remarks`, `branch_id`, `birthday`, `date_hired`, `address`, `tin`, `sss_number`, `philhealth_number`, `pagibig_number`, `emergency_contact_name`, `emergency_contact_number`, `salary_type`, `worker_type`, `declaration_status`, `default_daily_rate`, `default_monthly_salary`, `default_auction_rate`, `default_container_rate`, `default_ot_hour_rate`, `default_ot_minute_rate`)
VALUES ('be29ddd9-d6df-4715-bef0-f806976a4e58', 'DARWIN', NULL, 'DECEMBRIANO', NULL, 'REGULAR', 'ACTIVE', NULL, NULL, 'bd163cce-98e5-4513-b69e-875bd89c5f5c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FIXED_MONTHLY', 'REGULAR_WORKER', 'NON_DECLARED', NULL, 6000, 700, 700, 93.75, 1.56);

INSERT IGNORE INTO `employees` (`employee_id`, `first_name`, `middle_name`, `last_name`, `position`, `employee_type`, `status`, `contact_number`, `remarks`, `branch_id`, `birthday`, `date_hired`, `address`, `tin`, `sss_number`, `philhealth_number`, `pagibig_number`, `emergency_contact_name`, `emergency_contact_number`, `salary_type`, `worker_type`, `declaration_status`, `default_daily_rate`, `default_monthly_salary`, `default_auction_rate`, `default_container_rate`, `default_ot_hour_rate`, `default_ot_minute_rate`)
VALUES ('0d464b42-3350-4ce8-bd77-d35a84fe2351', 'JOSEPH', NULL, 'ENRIQUEZ', NULL, 'REGULAR', 'ACTIVE', NULL, NULL, 'bd163cce-98e5-4513-b69e-875bd89c5f5c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FIXED_MONTHLY', 'REGULAR_WORKER', 'NON_DECLARED', NULL, 5400, 700, 1400, 93.75, 1.56);

INSERT IGNORE INTO `employees` (`employee_id`, `first_name`, `middle_name`, `last_name`, `position`, `employee_type`, `status`, `contact_number`, `remarks`, `branch_id`, `birthday`, `date_hired`, `address`, `tin`, `sss_number`, `philhealth_number`, `pagibig_number`, `emergency_contact_name`, `emergency_contact_number`, `salary_type`, `worker_type`, `declaration_status`, `default_daily_rate`, `default_monthly_salary`, `default_auction_rate`, `default_container_rate`, `default_ot_hour_rate`, `default_ot_minute_rate`)
VALUES ('fb8bbd03-b207-4330-8951-84ccd98e5b79', 'WILVER', NULL, 'ERIA', NULL, 'REGULAR', 'ACTIVE', NULL, NULL, 'bd163cce-98e5-4513-b69e-875bd89c5f5c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FIXED_MONTHLY', 'REGULAR_WORKER', 'NON_DECLARED', 550, 5100, 700, 1400, 93.75, 1.56);

INSERT IGNORE INTO `employees` (`employee_id`, `first_name`, `middle_name`, `last_name`, `position`, `employee_type`, `status`, `contact_number`, `remarks`, `branch_id`, `birthday`, `date_hired`, `address`, `tin`, `sss_number`, `philhealth_number`, `pagibig_number`, `emergency_contact_name`, `emergency_contact_number`, `salary_type`, `worker_type`, `declaration_status`, `default_daily_rate`, `default_monthly_salary`, `default_auction_rate`, `default_container_rate`, `default_ot_hour_rate`, `default_ot_minute_rate`)
VALUES ('461a8934-22e6-4e61-9e7b-fd5ce85f7dc7', 'RHANDOLF', NULL, 'KARUNUNGAN', NULL, 'REGULAR', 'ACTIVE', NULL, NULL, 'bd163cce-98e5-4513-b69e-875bd89c5f5c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FIXED_MONTHLY', 'REGULAR_WORKER', 'NON_DECLARED', NULL, 5700, 700, 700, 93.75, 1.56);

INSERT IGNORE INTO `employees` (`employee_id`, `first_name`, `middle_name`, `last_name`, `position`, `employee_type`, `status`, `contact_number`, `remarks`, `branch_id`, `birthday`, `date_hired`, `address`, `tin`, `sss_number`, `philhealth_number`, `pagibig_number`, `emergency_contact_name`, `emergency_contact_number`, `salary_type`, `worker_type`, `declaration_status`, `default_daily_rate`, `default_monthly_salary`, `default_auction_rate`, `default_container_rate`, `default_ot_hour_rate`, `default_ot_minute_rate`)
VALUES ('3abb95ae-6701-4c4d-959a-2dced19d3c73', 'MA. LIZA', NULL, 'LACAP', NULL, 'REGULAR', 'ACTIVE', NULL, NULL, 'bd163cce-98e5-4513-b69e-875bd89c5f5c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FIXED_MONTHLY', 'REGULAR_WORKER', 'NON_DECLARED', NULL, 6000, 700, NULL, 93.75, 1.56);

INSERT IGNORE INTO `employees` (`employee_id`, `first_name`, `middle_name`, `last_name`, `position`, `employee_type`, `status`, `contact_number`, `remarks`, `branch_id`, `birthday`, `date_hired`, `address`, `tin`, `sss_number`, `philhealth_number`, `pagibig_number`, `emergency_contact_name`, `emergency_contact_number`, `salary_type`, `worker_type`, `declaration_status`, `default_daily_rate`, `default_monthly_salary`, `default_auction_rate`, `default_container_rate`, `default_ot_hour_rate`, `default_ot_minute_rate`)
VALUES ('4ba90c67-b474-45df-af99-b1b4359365e5', 'GENNA', NULL, 'MANALAYSAY', NULL, 'REGULAR', 'ACTIVE', NULL, NULL, 'bd163cce-98e5-4513-b69e-875bd89c5f5c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FIXED_MONTHLY', 'REGULAR_WORKER', 'NON_DECLARED', NULL, 6600, 700, NULL, 93.75, 1.56);

INSERT IGNORE INTO `employees` (`employee_id`, `first_name`, `middle_name`, `last_name`, `position`, `employee_type`, `status`, `contact_number`, `remarks`, `branch_id`, `birthday`, `date_hired`, `address`, `tin`, `sss_number`, `philhealth_number`, `pagibig_number`, `emergency_contact_name`, `emergency_contact_number`, `salary_type`, `worker_type`, `declaration_status`, `default_daily_rate`, `default_monthly_salary`, `default_auction_rate`, `default_container_rate`, `default_ot_hour_rate`, `default_ot_minute_rate`)
VALUES ('75dfba79-440c-4891-9c57-d032795cc4ef', 'JESSICA KEITH', NULL, 'MARILLA', NULL, 'REGULAR', 'ACTIVE', NULL, NULL, 'bd163cce-98e5-4513-b69e-875bd89c5f5c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FIXED_MONTHLY', 'REGULAR_WORKER', 'DECLARED', NULL, 6930, 730, NULL, 98, 1.64);

INSERT IGNORE INTO `employees` (`employee_id`, `first_name`, `middle_name`, `last_name`, `position`, `employee_type`, `status`, `contact_number`, `remarks`, `branch_id`, `birthday`, `date_hired`, `address`, `tin`, `sss_number`, `philhealth_number`, `pagibig_number`, `emergency_contact_name`, `emergency_contact_number`, `salary_type`, `worker_type`, `declaration_status`, `default_daily_rate`, `default_monthly_salary`, `default_auction_rate`, `default_container_rate`, `default_ot_hour_rate`, `default_ot_minute_rate`)
VALUES ('eaacc7d8-f654-4801-83a9-d99cd041b313', 'ROJEAN', NULL, 'MOTAS', NULL, 'REGULAR', 'ACTIVE', NULL, NULL, 'bd163cce-98e5-4513-b69e-875bd89c5f5c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FIXED_MONTHLY', 'REGULAR_WORKER', 'NON_DECLARED', NULL, 6600, 700, NULL, 93.75, 1.56);

INSERT IGNORE INTO `employees` (`employee_id`, `first_name`, `middle_name`, `last_name`, `position`, `employee_type`, `status`, `contact_number`, `remarks`, `branch_id`, `birthday`, `date_hired`, `address`, `tin`, `sss_number`, `philhealth_number`, `pagibig_number`, `emergency_contact_name`, `emergency_contact_number`, `salary_type`, `worker_type`, `declaration_status`, `default_daily_rate`, `default_monthly_salary`, `default_auction_rate`, `default_container_rate`, `default_ot_hour_rate`, `default_ot_minute_rate`)
VALUES ('a310df74-1b22-4404-b434-02e25b0cc6cc', 'RYAN', NULL, 'PETEZA', NULL, 'REGULAR', 'ACTIVE', NULL, NULL, 'bd163cce-98e5-4513-b69e-875bd89c5f5c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FIXED_MONTHLY', 'REGULAR_WORKER', 'NON_DECLARED', NULL, 5400, 700, 1400, 93.75, 1.56);

INSERT IGNORE INTO `employees` (`employee_id`, `first_name`, `middle_name`, `last_name`, `position`, `employee_type`, `status`, `contact_number`, `remarks`, `branch_id`, `birthday`, `date_hired`, `address`, `tin`, `sss_number`, `philhealth_number`, `pagibig_number`, `emergency_contact_name`, `emergency_contact_number`, `salary_type`, `worker_type`, `declaration_status`, `default_daily_rate`, `default_monthly_salary`, `default_auction_rate`, `default_container_rate`, `default_ot_hour_rate`, `default_ot_minute_rate`)
VALUES ('d82bb3b0-e7e1-49dc-9e0b-2d8b9e7d0157', 'NORILYN', NULL, 'PRAGA', NULL, 'REGULAR', 'ACTIVE', NULL, NULL, 'bd163cce-98e5-4513-b69e-875bd89c5f5c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FIXED_MONTHLY', 'REGULAR_WORKER', 'NON_DECLARED', NULL, 6000, 700, NULL, 93.75, 1.56);

INSERT IGNORE INTO `employees` (`employee_id`, `first_name`, `middle_name`, `last_name`, `position`, `employee_type`, `status`, `contact_number`, `remarks`, `branch_id`, `birthday`, `date_hired`, `address`, `tin`, `sss_number`, `philhealth_number`, `pagibig_number`, `emergency_contact_name`, `emergency_contact_number`, `salary_type`, `worker_type`, `declaration_status`, `default_daily_rate`, `default_monthly_salary`, `default_auction_rate`, `default_container_rate`, `default_ot_hour_rate`, `default_ot_minute_rate`)
VALUES ('e9549007-d491-4ee3-9bed-79dc8b5ab705', 'JESSICA', NULL, 'RUFLOE', NULL, 'REGULAR', 'ACTIVE', NULL, NULL, 'bd163cce-98e5-4513-b69e-875bd89c5f5c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FIXED_MONTHLY', 'REGULAR_WORKER', 'NON_DECLARED', NULL, 6600, 700, NULL, 93.75, 1.56);

INSERT IGNORE INTO `employees` (`employee_id`, `first_name`, `middle_name`, `last_name`, `position`, `employee_type`, `status`, `contact_number`, `remarks`, `branch_id`, `birthday`, `date_hired`, `address`, `tin`, `sss_number`, `philhealth_number`, `pagibig_number`, `emergency_contact_name`, `emergency_contact_number`, `salary_type`, `worker_type`, `declaration_status`, `default_daily_rate`, `default_monthly_salary`, `default_auction_rate`, `default_container_rate`, `default_ot_hour_rate`, `default_ot_minute_rate`)
VALUES ('f7c830f8-b83b-455f-b5bd-52739b0b8812', 'MARICA', NULL, 'SANAO', NULL, 'REGULAR', 'ACTIVE', NULL, NULL, 'bd163cce-98e5-4513-b69e-875bd89c5f5c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FIXED_MONTHLY', 'REGULAR_WORKER', 'DECLARED', NULL, 5700, 700, NULL, 93.75, 1.56);

INSERT IGNORE INTO `employees` (`employee_id`, `first_name`, `middle_name`, `last_name`, `position`, `employee_type`, `status`, `contact_number`, `remarks`, `branch_id`, `birthday`, `date_hired`, `address`, `tin`, `sss_number`, `philhealth_number`, `pagibig_number`, `emergency_contact_name`, `emergency_contact_number`, `salary_type`, `worker_type`, `declaration_status`, `default_daily_rate`, `default_monthly_salary`, `default_auction_rate`, `default_container_rate`, `default_ot_hour_rate`, `default_ot_minute_rate`)
VALUES ('041008a5-3802-4c0d-9a7d-310d1ffd8091', 'IRENE', NULL, 'SASAKI', NULL, 'REGULAR', 'ACTIVE', NULL, NULL, 'bd163cce-98e5-4513-b69e-875bd89c5f5c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FIXED_MONTHLY', 'REGULAR_WORKER', 'NON_DECLARED', NULL, 100000, NULL, NULL, NULL, NULL);

INSERT IGNORE INTO `employees` (`employee_id`, `first_name`, `middle_name`, `last_name`, `position`, `employee_type`, `status`, `contact_number`, `remarks`, `branch_id`, `birthday`, `date_hired`, `address`, `tin`, `sss_number`, `philhealth_number`, `pagibig_number`, `emergency_contact_name`, `emergency_contact_number`, `salary_type`, `worker_type`, `declaration_status`, `default_daily_rate`, `default_monthly_salary`, `default_auction_rate`, `default_container_rate`, `default_ot_hour_rate`, `default_ot_minute_rate`)
VALUES ('983bc2f5-ac89-4641-9061-b5906fabf3d8', 'JEAN PAUL', NULL, 'SILLORIQUEZ', NULL, 'REGULAR', 'ACTIVE', NULL, NULL, 'bd163cce-98e5-4513-b69e-875bd89c5f5c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FIXED_MONTHLY', 'REGULAR_WORKER', 'DECLARED', NULL, 10500, NULL, NULL, NULL, NULL);

INSERT IGNORE INTO `employees` (`employee_id`, `first_name`, `middle_name`, `last_name`, `position`, `employee_type`, `status`, `contact_number`, `remarks`, `branch_id`, `birthday`, `date_hired`, `address`, `tin`, `sss_number`, `philhealth_number`, `pagibig_number`, `emergency_contact_name`, `emergency_contact_number`, `salary_type`, `worker_type`, `declaration_status`, `default_daily_rate`, `default_monthly_salary`, `default_auction_rate`, `default_container_rate`, `default_ot_hour_rate`, `default_ot_minute_rate`)
VALUES ('43ecb22b-31c2-44ff-bfb2-4f13127ca46f', 'GESEBEL', NULL, 'SUNDIAM', NULL, 'REGULAR', 'ACTIVE', NULL, NULL, 'bd163cce-98e5-4513-b69e-875bd89c5f5c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FIXED_MONTHLY', 'REGULAR_WORKER', 'DECLARED', NULL, 10500, NULL, NULL, NULL, NULL);
